// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Input as OrdinaryInput;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Output as OrdinaryOutput;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Input as MetaInput;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Output as MetaOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaWrite(SemaWriteInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput(OrdinaryInput),
    MetaInput(MetaInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput(OrdinaryOutput),
    MetaOutput(MetaOutput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusInput {
    SignalArrived(SignalArrived),
    SemaReadCompleted(SemaReadCompleted),
    SemaWriteCompleted(SemaWriteCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusOutput {
    CommandSemaRead(CommandSemaRead),
    CommandSemaWrite(CommandSemaWrite),
    ReplyToSignal(ReplyToSignal),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaReadCompleted(SemaReadCompleted),
    SemaWriteCompleted(SemaWriteCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    CommandSemaRead(CommandSemaRead),
    CommandSemaWrite(CommandSemaWrite),
    ReplyToSignal(ReplyToSignal),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn new(payload: SemaWriteInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteInput> for CommandSemaWrite {
    fn from(payload: SemaWriteInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusInput {
        &self.0
    }
    pub fn into_payload(self) -> NexusInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusInput> for Continue {
    fn from(payload: NexusInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SignalInput {
    pub fn ordinary_input(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
    pub fn meta_input(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl SignalOutput {
    pub fn ordinary_output(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
    pub fn meta_output(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl NexusInput {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusOutput {
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn r#continue(payload: NexusInput) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn r#continue(payload: NexusInput) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<OrdinaryInput> for SignalInput {
    fn from(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaInput> for SignalInput {
    fn from(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryOutput> for SignalOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaOutput> for SignalOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusInput {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusInput {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusInput {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusOutput {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusOutput {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusOutput {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusOutput {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for Input {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for Input {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for Output {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for Output {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
