// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_domain_criome::schema::lib::Input as OrdinaryInput;
pub use signal_domain_criome::schema::lib::Output as OrdinaryOutput;
pub use meta_signal_domain_criome::schema::lib::Input as MetaInput;
pub use meta_signal_domain_criome::schema::lib::Output as MetaOutput;
pub use crate::schema::sema::ReadInput as SemaReadInput;
pub use crate::schema::sema::ReadOutput as SemaReadOutput;
pub use crate::schema::sema::WriteInput as SemaWriteInput;
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

pub type SignalArrived = SignalInput;

pub type SemaReadCompleted = SemaReadOutput;

pub type SemaWriteCompleted = SemaWriteOutput;

pub type CommandSemaRead = SemaReadInput;

pub type CommandSemaWrite = SemaWriteInput;

pub type ReplyToSignal = SignalOutput;

pub type Continue = NexusInput;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput,
    MetaInput,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput,
    MetaOutput,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusInput {
    SignalArrived,
    SemaReadCompleted,
    SemaWriteCompleted,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusOutput {
    CommandSemaRead,
    CommandSemaWrite,
    ReplyToSignal,
    Continue,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaReadCompleted(SemaReadCompleted),
    SemaWriteCompleted(SemaWriteCompleted),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    CommandSemaRead(CommandSemaRead),
    CommandSemaWrite(CommandSemaWrite),
    ReplyToSignal(ReplyToSignal),
    Continue(Continue),
}

impl Input {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

impl Output {
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[cfg(feature = "nota-text")]
impl SignalInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SignalOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
