// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_domain_criome::schema::lib::Observation as Observation;
pub use signal_domain_criome::schema::lib::ResolutionQuery as ResolutionQuery;
pub use signal_domain_criome::schema::lib::ProjectionQuery as ProjectionQuery;
pub use signal_domain_criome::schema::lib::Validation as Validation;
pub use signal_domain_criome::schema::lib::Observed as Observed;
pub use signal_domain_criome::schema::lib::Resolved as Resolved;
pub use signal_domain_criome::schema::lib::Projected as Projected;
pub use signal_domain_criome::schema::lib::Validated as Validated;
pub use signal_domain_criome::schema::lib::Domain as Domain;
pub use signal_domain_criome::schema::lib::Projection as Projection;
pub use meta_signal_domain_criome::schema::lib::Registration as Registration;
pub use meta_signal_domain_criome::schema::lib::Delegation as Delegation;
pub use meta_signal_domain_criome::schema::lib::Retirement as Retirement;
pub use meta_signal_domain_criome::schema::lib::Policy as Policy;
pub use meta_signal_domain_criome::schema::lib::ProjectionDeclaration as ProjectionDeclaration;
pub use meta_signal_domain_criome::schema::lib::DomainRegistered as DomainRegistered;
pub use meta_signal_domain_criome::schema::lib::DelegationSet as DelegationSet;
pub use meta_signal_domain_criome::schema::lib::DomainRetired as DomainRetired;
pub use meta_signal_domain_criome::schema::lib::PolicySet as PolicySet;
pub use meta_signal_domain_criome::schema::lib::ProjectionSet as ProjectionSet;
pub use meta_signal_domain_criome::schema::lib::RequestRejected as RequestRejected;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    Observe,
    Resolve,
    Project,
    Validate,
}

pub type Observe = Observation;

pub type Resolve = ResolutionQuery;

pub type Project = ProjectionQuery;

pub type Validate = Validation;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    Observed,
    Resolved,
    Projected,
    Validated,
    Missed,
}

pub type Missed = RejectionReport;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

pub type RegisterDomain = Registration;

pub type Delegate = Delegation;

pub type RetireDomain = Retirement;

pub type SetPolicy = Policy;

pub type SetProjection = ProjectionDeclaration;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    DomainRegistered,
    DelegationSet,
    DomainRetired,
    PolicySet,
    ProjectionSet,
    RequestRejected,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    DomainUnknown,
    NotAuthoritative,
    DomainAlreadyRegistered,
    ProjectionRejected,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistryTable {
    pub domains: Vec<RegisteredDomain>,
    pub delegations: Vec<DelegationRecord>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisteredDomain {
    pub domain: Domain,
    pub authority: AuthorityEndpoint,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationRecord {
    pub domain: Domain,
    pub authority: AuthorityEndpoint,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionTable(pub Vec<ProjectionRecord>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionRecord {
    pub domain: Domain,
    pub projection: Projection,
    pub marker: StateMarker,
}

pub type AuthorityEndpoint = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ReadInput(ReadInput),
    WriteInput(WriteInput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReadOutput(ReadOutput),
    WriteOutput(WriteOutput),
}

impl ProjectionTable {
    pub fn new(payload: Vec<ProjectionRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ProjectionRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ProjectionRecord> {
        self.0
    }
}
impl From<Vec<ProjectionRecord>> for ProjectionTable {
    fn from(payload: Vec<ProjectionRecord>) -> Self {
        Self::new(payload)
    }
}

impl Input {
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

impl Output {
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[cfg(feature = "nota-text")]
impl ReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl WriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl WriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl StateMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RegistryTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RegisteredDomain {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DelegationRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    Observe,
    Resolve,
    Project,
    Validate,
}

impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::Observe => ReadInputRoute::Observe,
            Self::Resolve => ReadInputRoute::Resolve,
            Self::Project => ReadInputRoute::Project,
            Self::Validate => ReadInputRoute::Validate,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    Observed,
    Resolved,
    Projected,
    Validated,
    Missed,
}

impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::Observed => ReadOutputRoute::Observed,
            Self::Resolved => ReadOutputRoute::Resolved,
            Self::Projected => ReadOutputRoute::Projected,
            Self::Validated => ReadOutputRoute::Validated,
            Self::Missed => ReadOutputRoute::Missed,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::RegisterDomain => WriteInputRoute::RegisterDomain,
            Self::Delegate => WriteInputRoute::Delegate,
            Self::RetireDomain => WriteInputRoute::RetireDomain,
            Self::SetPolicy => WriteInputRoute::SetPolicy,
            Self::SetProjection => WriteInputRoute::SetProjection,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    DomainRegistered,
    DelegationSet,
    DomainRetired,
    PolicySet,
    ProjectionSet,
    RequestRejected,
}

impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::DomainRegistered => WriteOutputRoute::DomainRegistered,
            Self::DelegationSet => WriteOutputRoute::DelegationSet,
            Self::DomainRetired => WriteOutputRoute::DomainRetired,
            Self::PolicySet => WriteOutputRoute::PolicySet,
            Self::ProjectionSet => WriteOutputRoute::ProjectionSet,
            Self::RequestRejected => WriteOutputRoute::RequestRejected,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::RegisterDomain => "SemaWriteInputRegisterDomain",
                    WriteInputRoute::Delegate => "SemaWriteInputDelegate",
                    WriteInputRoute::RetireDomain => "SemaWriteInputRetireDomain",
                    WriteInputRoute::SetPolicy => "SemaWriteInputSetPolicy",
                    WriteInputRoute::SetProjection => "SemaWriteInputSetProjection",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::Observe => "SemaReadInputObserve",
                    ReadInputRoute::Resolve => "SemaReadInputResolve",
                    ReadInputRoute::Project => "SemaReadInputProject",
                    ReadInputRoute::Validate => "SemaReadInputValidate",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::DomainRegistered => {
                        "SemaWriteOutputDomainRegistered"
                    }
                    WriteOutputRoute::DelegationSet => "SemaWriteOutputDelegationSet",
                    WriteOutputRoute::DomainRetired => "SemaWriteOutputDomainRetired",
                    WriteOutputRoute::PolicySet => "SemaWriteOutputPolicySet",
                    WriteOutputRoute::ProjectionSet => "SemaWriteOutputProjectionSet",
                    WriteOutputRoute::RequestRejected => "SemaWriteOutputRequestRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::Observed => "SemaReadOutputObserved",
                    ReadOutputRoute::Resolved => "SemaReadOutputResolved",
                    ReadOutputRoute::Projected => "SemaReadOutputProjected",
                    ReadOutputRoute::Validated => "SemaReadOutputValidated",
                    ReadOutputRoute::Missed => "SemaReadOutputMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl triad_runtime::SemaWriteInput for WriteInput {}

impl triad_runtime::SemaWriteOutput for WriteOutput {}

impl triad_runtime::SemaReadInput for ReadInput {}

impl triad_runtime::SemaReadOutput for ReadOutput {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "actor resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "actor configuration invalid: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStartFailure {}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "actor resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "actor child still running: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStopFailure {}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
