// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Observation as Observation;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::ResolutionQuery as ResolutionQuery;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::ProjectionQuery as ProjectionQuery;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Validation as Validation;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Observed as Observed;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Resolved as Resolved;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Projected as Projected;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Validated as Validated;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Domain as Domain;
#[rustfmt::skip]
pub use signal_domain_criome::schema::lib::Projection as Projection;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Registration as Registration;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Delegation as Delegation;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Retirement as Retirement;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::Policy as Policy;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::ProjectionDeclaration as ProjectionDeclaration;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::DomainRegistered as DomainRegistered;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::DelegationSet as DelegationSet;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::DomainRetired as DomainRetired;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::PolicySet as PolicySet;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::ProjectionSet as ProjectionSet;
#[rustfmt::skip]
pub use meta_signal_domain_criome::schema::lib::RequestRejected as RequestRejected;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    Observe(Observe),
    Resolve(Resolve),
    Project(Project),
    Validate(Validate),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observe(Observation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Resolve(ResolutionQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Project(ProjectionQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validate(Validation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    Observed(Observed),
    Resolved(Resolved),
    Projected(Projected),
    Validated(Validated),
    Missed(Missed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Missed(RejectionReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    RegisterDomain(RegisterDomain),
    Delegate(Delegate),
    RetireDomain(RetireDomain),
    SetPolicy(SetPolicy),
    SetProjection(SetProjection),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterDomain(Registration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegate(Delegation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireDomain(Retirement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetPolicy(Policy);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetProjection(ProjectionDeclaration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    DomainRegistered(DomainRegistered),
    DelegationSet(DelegationSet),
    DomainRetired(DomainRetired),
    PolicySet(PolicySet),
    ProjectionSet(ProjectionSet),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    DomainUnknown,
    NotAuthoritative,
    DomainAlreadyRegistered,
    ProjectionRejected,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistryTable {
    pub domains: Vec<RegisteredDomain>,
    pub delegations: Vec<DelegationRecord>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisteredDomain {
    pub domain: Domain,
    pub authority: AuthorityEndpoint,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationRecord {
    pub domain: Domain,
    pub authority: AuthorityEndpoint,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionTable(Vec<ProjectionRecord>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionRecord {
    pub domain: Domain,
    pub projection: Projection,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorityEndpoint(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ReadInput(ReadInput),
    WriteInput(WriteInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReadOutput(ReadOutput),
    WriteOutput(WriteOutput),
}

#[rustfmt::skip]
impl Observe {
    pub fn new(payload: Observation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Observation {
        &self.0
    }
    pub fn into_payload(self) -> Observation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Observation> for Observe {
    fn from(payload: Observation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Resolve {
    pub fn new(payload: ResolutionQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ResolutionQuery {
        &self.0
    }
    pub fn into_payload(self) -> ResolutionQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ResolutionQuery> for Resolve {
    fn from(payload: ResolutionQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Project {
    pub fn new(payload: ProjectionQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProjectionQuery {
        &self.0
    }
    pub fn into_payload(self) -> ProjectionQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProjectionQuery> for Project {
    fn from(payload: ProjectionQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validate {
    pub fn new(payload: Validation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Validation {
        &self.0
    }
    pub fn into_payload(self) -> Validation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Validation> for Validate {
    fn from(payload: Validation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Missed {
    pub fn new(payload: RejectionReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReport {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReport> for Missed {
    fn from(payload: RejectionReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterDomain {
    pub fn new(payload: Registration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Registration {
        &self.0
    }
    pub fn into_payload(self) -> Registration {
        self.0
    }
}
#[rustfmt::skip]
impl From<Registration> for RegisterDomain {
    fn from(payload: Registration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Delegate {
    pub fn new(payload: Delegation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Delegation {
        &self.0
    }
    pub fn into_payload(self) -> Delegation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Delegation> for Delegate {
    fn from(payload: Delegation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireDomain {
    pub fn new(payload: Retirement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Retirement {
        &self.0
    }
    pub fn into_payload(self) -> Retirement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Retirement> for RetireDomain {
    fn from(payload: Retirement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetPolicy {
    pub fn new(payload: Policy) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Policy {
        &self.0
    }
    pub fn into_payload(self) -> Policy {
        self.0
    }
}
#[rustfmt::skip]
impl From<Policy> for SetPolicy {
    fn from(payload: Policy) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetProjection {
    pub fn new(payload: ProjectionDeclaration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProjectionDeclaration {
        &self.0
    }
    pub fn into_payload(self) -> ProjectionDeclaration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProjectionDeclaration> for SetProjection {
    fn from(payload: ProjectionDeclaration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDigest {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StateDigest {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProjectionTable {
    pub fn new(payload: Vec<ProjectionRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ProjectionRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ProjectionRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ProjectionRecord>> for ProjectionTable {
    fn from(payload: Vec<ProjectionRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorityEndpoint {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AuthorityEndpoint {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(Observe::new(payload))
    }
    pub fn resolve(payload: ResolutionQuery) -> Self {
        Self::Resolve(Resolve::new(payload))
    }
    pub fn project(payload: ProjectionQuery) -> Self {
        Self::Project(Project::new(payload))
    }
    pub fn validate(payload: Validation) -> Self {
        Self::Validate(Validate::new(payload))
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn observed(payload: Observed) -> Self {
        Self::Observed(payload)
    }
    pub fn resolved(payload: Resolved) -> Self {
        Self::Resolved(payload)
    }
    pub fn projected(payload: Projected) -> Self {
        Self::Projected(payload)
    }
    pub fn validated(payload: Validated) -> Self {
        Self::Validated(payload)
    }
    pub fn missed(payload: RejectionReport) -> Self {
        Self::Missed(Missed::new(payload))
    }
}

#[rustfmt::skip]
impl WriteInput {
    pub fn register_domain(payload: Registration) -> Self {
        Self::RegisterDomain(RegisterDomain::new(payload))
    }
    pub fn delegate(payload: Delegation) -> Self {
        Self::Delegate(Delegate::new(payload))
    }
    pub fn retire_domain(payload: Retirement) -> Self {
        Self::RetireDomain(RetireDomain::new(payload))
    }
    pub fn set_policy(payload: Policy) -> Self {
        Self::SetPolicy(SetPolicy::new(payload))
    }
    pub fn set_projection(payload: ProjectionDeclaration) -> Self {
        Self::SetProjection(SetProjection::new(payload))
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn domain_registered(payload: DomainRegistered) -> Self {
        Self::DomainRegistered(payload)
    }
    pub fn delegation_set(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
    pub fn domain_retired(payload: DomainRetired) -> Self {
        Self::DomainRetired(payload)
    }
    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
    pub fn projection_set(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Observe> for ReadInput {
    fn from(payload: Observe) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<Resolve> for ReadInput {
    fn from(payload: Resolve) -> Self {
        Self::Resolve(payload)
    }
}

#[rustfmt::skip]
impl From<Project> for ReadInput {
    fn from(payload: Project) -> Self {
        Self::Project(payload)
    }
}

#[rustfmt::skip]
impl From<Validate> for ReadInput {
    fn from(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

#[rustfmt::skip]
impl From<Observed> for ReadOutput {
    fn from(payload: Observed) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<Resolved> for ReadOutput {
    fn from(payload: Resolved) -> Self {
        Self::Resolved(payload)
    }
}

#[rustfmt::skip]
impl From<Projected> for ReadOutput {
    fn from(payload: Projected) -> Self {
        Self::Projected(payload)
    }
}

#[rustfmt::skip]
impl From<Validated> for ReadOutput {
    fn from(payload: Validated) -> Self {
        Self::Validated(payload)
    }
}

#[rustfmt::skip]
impl From<Missed> for ReadOutput {
    fn from(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterDomain> for WriteInput {
    fn from(payload: RegisterDomain) -> Self {
        Self::RegisterDomain(payload)
    }
}

#[rustfmt::skip]
impl From<Delegate> for WriteInput {
    fn from(payload: Delegate) -> Self {
        Self::Delegate(payload)
    }
}

#[rustfmt::skip]
impl From<RetireDomain> for WriteInput {
    fn from(payload: RetireDomain) -> Self {
        Self::RetireDomain(payload)
    }
}

#[rustfmt::skip]
impl From<SetPolicy> for WriteInput {
    fn from(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }
}

#[rustfmt::skip]
impl From<SetProjection> for WriteInput {
    fn from(payload: SetProjection) -> Self {
        Self::SetProjection(payload)
    }
}

#[rustfmt::skip]
impl From<DomainRegistered> for WriteOutput {
    fn from(payload: DomainRegistered) -> Self {
        Self::DomainRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<DelegationSet> for WriteOutput {
    fn from(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
}

#[rustfmt::skip]
impl From<DomainRetired> for WriteOutput {
    fn from(payload: DomainRetired) -> Self {
        Self::DomainRetired(payload)
    }
}

#[rustfmt::skip]
impl From<PolicySet> for WriteOutput {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

#[rustfmt::skip]
impl From<ProjectionSet> for WriteOutput {
    fn from(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
}

#[rustfmt::skip]
impl From<RequestRejected> for WriteOutput {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    Observe,
    Resolve,
    Project,
    Validate,
}

#[rustfmt::skip]
impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::Observe(_) => ReadInputRoute::Observe,
            Self::Resolve(_) => ReadInputRoute::Resolve,
            Self::Project(_) => ReadInputRoute::Project,
            Self::Validate(_) => ReadInputRoute::Validate,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    Observed,
    Resolved,
    Projected,
    Validated,
    Missed,
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::Observed(_) => ReadOutputRoute::Observed,
            Self::Resolved(_) => ReadOutputRoute::Resolved,
            Self::Projected(_) => ReadOutputRoute::Projected,
            Self::Validated(_) => ReadOutputRoute::Validated,
            Self::Missed(_) => ReadOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

#[rustfmt::skip]
impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::RegisterDomain(_) => WriteInputRoute::RegisterDomain,
            Self::Delegate(_) => WriteInputRoute::Delegate,
            Self::RetireDomain(_) => WriteInputRoute::RetireDomain,
            Self::SetPolicy(_) => WriteInputRoute::SetPolicy,
            Self::SetProjection(_) => WriteInputRoute::SetProjection,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    DomainRegistered,
    DelegationSet,
    DomainRetired,
    PolicySet,
    ProjectionSet,
    RequestRejected,
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::DomainRegistered(_) => WriteOutputRoute::DomainRegistered,
            Self::DelegationSet(_) => WriteOutputRoute::DelegationSet,
            Self::DomainRetired(_) => WriteOutputRoute::DomainRetired,
            Self::PolicySet(_) => WriteOutputRoute::PolicySet,
            Self::ProjectionSet(_) => WriteOutputRoute::ProjectionSet,
            Self::RequestRejected(_) => WriteOutputRoute::RequestRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::RegisterDomain => "SemaWriteInputRegisterDomain",
                    WriteInputRoute::Delegate => "SemaWriteInputDelegate",
                    WriteInputRoute::RetireDomain => "SemaWriteInputRetireDomain",
                    WriteInputRoute::SetPolicy => "SemaWriteInputSetPolicy",
                    WriteInputRoute::SetProjection => "SemaWriteInputSetProjection",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::Observe => "SemaReadInputObserve",
                    ReadInputRoute::Resolve => "SemaReadInputResolve",
                    ReadInputRoute::Project => "SemaReadInputProject",
                    ReadInputRoute::Validate => "SemaReadInputValidate",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::DomainRegistered => {
                        "SemaWriteOutputDomainRegistered"
                    }
                    WriteOutputRoute::DelegationSet => "SemaWriteOutputDelegationSet",
                    WriteOutputRoute::DomainRetired => "SemaWriteOutputDomainRetired",
                    WriteOutputRoute::PolicySet => "SemaWriteOutputPolicySet",
                    WriteOutputRoute::ProjectionSet => "SemaWriteOutputProjectionSet",
                    WriteOutputRoute::RequestRejected => "SemaWriteOutputRequestRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::Observed => "SemaReadOutputObserved",
                    ReadOutputRoute::Resolved => "SemaReadOutputResolved",
                    ReadOutputRoute::Projected => "SemaReadOutputProjected",
                    ReadOutputRoute::Validated => "SemaReadOutputValidated",
                    ReadOutputRoute::Missed => "SemaReadOutputMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for WriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for WriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for ReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for ReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
